### ISSUE TITLE
The entity linking process and original dataset

### ISSUE THREAD

**Issue by halaoyy** [Zzoay/disinformation_detection#1]
Hello,
Thank you for sharing your work!
It seems that the entity linking processes and the original dataset files are not included in this repository.
Would you mind to release them?

**Comment by Zzoay** [comment]
Thanks for your attention. Due to the entity linking process is conducted in another machine, we did not add them in this repo. We will release it soon. Besides, you should use the tool provided by [FakenewsNet](https://github.com/KaiDMML/FakeNewsNet) to access the dataset:
> Complete dataset cannot be distributed because of Twitter privacy policies and news publisher copy rights. Social engagements and user information are not disclosed because of Twitter Policy. This code repository can be used to download news articles from published websites and relevant social media data from Twitter.

**Comment by Zzoay** [comment]
The entity linking code is released now, in the link_entity.py file.

**Comment by halaoyy** [comment]
Thank you!
